package fp.tipos;

public enum Categoria {
	BAR, CAMA, ESTANTERÍA, ARMARIO, MUEBLECAFÉ, SILLA, CAJONERA, MUEBLENIÑOS, ENFERMERÍA,
	FUERA, DIVISOR, APARADOR, SOFÁ, MESA, CARROS, MUEBLETELE, ROPERO;

	
}
